### PR TITLE
Add support for successfully running eslint in windows

### PR DESCRIPTION
**Pull request by webteckie**
Added support for successfully running eslint in windows.

### CODE REVIEW

**Comment by bassjacob** [comment]
Can we validate that git will still strip CRLF on windows as well as linux/osx? otherwise we're in for a world of pain with whitespace changes for every line of code. 

additionally, does this mean that every repo that uses this config will need to also ship a .gitattributes file with `core.autocrlf input` set?

**Comment by webteckie** [comment]
@bassjacob can you please do that?  I  don't have either of them OSs.  As to your second question, I don't think so.  What makes you think that?

**Comment by bassjacob** [comment]
Sure, I can test it on the three OS's (MacOS, Linux and Windows) and validate that CRLF line endings are stripped.

My concern is that the point of the eslint rule is to remove the CRLF line endings, which is the default difference between windows and unix OS's. If you don't have the rule set, and save a file with CRLF endings and a unix user edits the same file, they'll see a bunch of extra "^M" chars at the line endings in the file, likely leading to a bunch of whitespace changes as the file is edited between the two OS's.

**Comment by webteckie** [comment]
@bassjacob I've done quite a few changes in keystone using my windows environment and never had an issue with CRLF getting messed up.  So I think we good there :-)  My issue was running the eslint and this change addresses that.

**Comment by webteckie** [comment]
@bassjacob it dawned on me what you mean now.  Yeah, most likely it will break line endings if windows users start modifying code with this rule.  I will close for now.

**Pull request closed without merging**
